export const PATHS = {
  Home: 'Home',
  Result: 'Result',
  ReminderSet: 'ReminderSet',
  Splash: 'Splash',
  Onboard: 'Onboard',
  LoginRegister: 'LoginRegister',
  ChangePassword: 'ChangePassword',
  Trial: 'Trial',
  OtpRegister: 'OtpRegister',
  OtpForgot: 'OtpForgot',
  CreateNewPassword: 'CreateNewPassword',
  Dashboard: 'Dashboard',
  Settings: 'Settings',
  AboutUs: 'AboutUs',
  PrivacyPolicy: 'PrivacyPolicy',
  Terms: 'Terms',
  ContactUs: 'ContactUs',
  MyProfile: 'MyProfile',
  Gallery: 'Gallery',
  UploadPhoto: 'UploadPhoto',
  Subscription: 'Subscription',
  SubscriptionPackages: 'SubscriptionPackages',
  Update: 'Update',
  Camera: 'Camera',
  GalleryDetails: 'GalleryDetails',
} as const;
